### ISSUE TITLE
position无法修改 希望增加可以自定义样式的 className API

### ISSUE THREAD

**Issue by 1039958384** [tinper-bee/bee-loading#2]
在项目中发现 loading只能遮罩浏览器的第一屏，当拖动滚动条，滚动到底部页面时，还是可以对页面进行操作。应用场景是遮罩整个页面。所以应该增加一个className 的API 使得后续样式可以自定义

**Comment by HuYuee** [comment]
可以使用fullScreen参数，或者下载新版使用wrapperClassName参数自定义样式。
